name = "AppleSkin"
filename = "appleskin-fabric-mc1.17.1-2.2.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/EsAfCjCV/versions/fabric-mc1.17.1-2.2.0/appleskin-fabric-mc1.17.1-2.2.0.jar"
hash-format = "sha1"
hash = "f04392ba7d68a971df6d7a62bb0bb4fb3af59558"

[update]
[update.modrinth]
mod-id = "EsAfCjCV"
version = "tqCi5b3L"
