name = "Applied Energistics 2"
filename = "appliedenergistics2-9.0.0-beta.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3520/658/appliedenergistics2-9.0.0-beta.2.jar"
hash-format = "sha1"
hash = "146c77c03818e6f11597175251d4670918e4fb08"

[update]
[update.curseforge]
file-id = 3520658
project-id = 223794
