name = "Bits And Chisels"
filename = "bitsandchisels-2.6.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/q8MC5tW2/versions/2.6.0/bitsandchisels-2.6.0.jar"
hash-format = "sha1"
hash = "17692f8aa15cdfd161378f671b32303bfa9e8ec2"

[update]
[update.modrinth]
mod-id = "q8MC5tW2"
version = "R6yT6sYW"
