name = "Carpet"
filename = "fabric-carpet-1.17.1-1.4.57+v220119.jar"
side = "server"

[download]
url = "https://github.com/gnembon/fabric-carpet/releases/download/1.4.57/fabric-carpet-1.17.1-1.4.57+v220119.jar"

# A number of tools can generate the hash for you, including 7-zip and sha256sum
# packwiz supports a number of hashes, including sha256, sha512, sha1 and md5
hash-format = "sha256"
hash = "C7549EB66771432C482D4B53DDACC5398028C312F7F9FA41D395B4EE68D9FEA7"