name = "Charm"
filename = "charm-fabric-1.17-3.3.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/pOQTcQmj/versions/3.3.0/charm-fabric-1.17-3.3.0.jar"
hash-format = "sha1"
hash = "9151a81eaf408cd095ae1475aa106a76a05436ba"

[update]
[update.modrinth]
mod-id = "pOQTcQmj"
version = "QQvQAo20"
