name = "Connectible Chains [Fabric]"
filename = "connectiblechains-1.17.1-1.2.3.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/ykSfIgTw/versions/1.17.1-1.2.3/connectiblechains-1.17.1-1.2.3.jar"
hash-format = "sha1"
hash = "2e1687504655a2bf7276893ca1fde5dd8d9f6420"

[update]
[update.modrinth]
mod-id = "ykSfIgTw"
version = "5veQpRBB"
