name = "Head Index"
filename = "headindex-1.0.3.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/mEPmyd7J/versions/1.0.3/headindex-1.0.3.jar"
hash-format = "sha1"
hash = "493dd4d5185c7d7994c6aed7382be90c443cbc6b"

[update]
[update.modrinth]
mod-id = "mEPmyd7J"
version = "8bPWlZzx"
