name = "Nether Chest"
filename = "netherchest-mc1.17.1-3.1.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/okOUGirG/versions/mc1.17.1-3.1/netherchest-mc1.17.1-3.1.jar"
hash-format = "sha1"
hash = "c77ba740ed14b79900f3fd292672dab9e48f918f"

[update]
[update.modrinth]
mod-id = "okOUGirG"
version = "eOPiheBh"
