name = "Plant In A Jar"
filename = "plantinajar-2.2.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/6T8A0G0v/versions/2.2.2/plantinajar-2.2.2.jar"
hash-format = "sha1"
hash = "de141652898532fc98bebd55ee20c989db516b44"

[update]
[update.modrinth]
mod-id = "6T8A0G0v"
version = "Zqf6Hlif"
