name = "Quartz Elevator"
filename = "quartz-elevator-1.3.0+1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3614/703/quartz-elevator-1.3.0+1.17.jar"
hash-format = "sha1"
hash = "28198b9bf06c5a658c2aabf309ca18f1cf4cd909"

[update]
[update.curseforge]
file-id = 3614703
project-id = 442509
