name = "Tiny Trash Can"
filename = "ttc-1.3.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com//data/nGy7n4bj/versions/1.3.0/ttc-1.3.0.jar"
hash-format = "sha1"
hash = "7df84f8b69a9fd85663847c9d851d73117b170be"

[update]
[update.modrinth]
mod-id = "nGy7n4bj"
version = "2iG2szBu"
