name = "Twigs"
filename = "twigs-1.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3455/185/twigs-1.0.2.jar"
hash-format = "sha1"
hash = "37c7b878ea958829d6a0187e16a9e5d1c80c20e1"

[update]
[update.curseforge]
file-id = 3455185
project-id = 496913
