name = "Wireless Networks"
filename = "wirelessnetworks-1.3.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3504/367/wirelessnetworks-1.3.1.jar"
hash-format = "sha1"
hash = "bbd9404233986ba057368c89523802efd12cac0a"

[update]
[update.curseforge]
file-id = 3504367
project-id = 461316
